{% set name = "spyrmsd" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4040eb6b4fc7c562ef4cae9b0780462ddefecce63f34f4a497b1336ca0fd658a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - rustworkx

test:
  requires:
    - python {{ python_min }}
  imports:
    - spyrmsd

about:
  home: https://github.com/RMeli/spyrmsd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symmetry-corrected RMSD

  description: |
    Symmetry-corrected RMSD
  doc_url: https://spyrmsd.readthedocs.io/en/master/
  dev_url: https://github.com/RMeli/spyrmsd

extra:
  recipe-maintainers:
    - RMeli
